#https://help.github.com/en/actions/language-and-framework-guides/publishing-docker-images#publishing-images-to-github-packages
name: Publish Docker image
on:
  push:
    # Publish  on `master` and `development` 
    branches:
      - master
      - development
      - test_docker_unit

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: automl/auto-sklearn/auto-sklearn
          tag_with_ref: true
      - name: Docker Login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
        env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Pull Docker image
        run: docker pull "docker.pkg.github.com/$GITHUB_REPOSITORY/auto-sklearn:latest"
      - name: Run image
        run: docker run -it -d --name unittester -v $GITHUB_WORKSPACE:/workspace -w /workspace docker.pkg.github.com/$GITHUB_REPOSITORY/auto-sklearn:latest
      - name: Run unit testing
        run: python -m pytest -v test
